.github/workflows/codeql-analysis.yaml
Add CodeQL github action for Python and JavaScript
=> [monorepo] feat: Add CodeQL

.gitmodules, seed-job/Jenkinsfile, seed-job/buildConfiguration.yaml
Remove the ``seed-job`` folder since it is under jenkins folder
=> [monorepo] fix: remove seed folder

optin/puller/puller/db/CompletedOptinDatabase.py, optin/puller/puller/db/InProgressOptinDatabase.py, optin/puller/puller/models/OptinRequest.py, optin/puller/puller/processors/NemOptinProcessor.py, optin/puller/tests/db/test_CompletedOptinDatabase.py, optin/puller/tests/db/test_InProgressOptinDatabase.py, optin/puller/tests/models/test_OptinRequest.py, optin/puller/tests/test/DatabaseTestUtils.py, optin/puller/workflows/download_postoptin.py
1. rename OptinDatabase to CompletedOptinDatabase
2. add InProgressDatabase for storing errors and in progress requests
3. separate models into own directory
4. store addresses and hashes in db as blob instead of text 
5. integrate [2] into workflow
=> [puller/optin]: feature add in progress database

optin/puller/.coveragerc, optin/puller/Jenkinsfile
Enable code coverage upload for the puller
=> [optin/puller] fix: enable code coverage

optin/puller/puller/client/SymbolClient.py, optin/puller/tests/client/test_SymbolClient.py, optin/puller/workflows/generate_postoptin.py
I'm missing client.redeem test, but please take a look
=> [puller] download post-optin

.github/buildConfiguration.yaml, optin/reporting/Jenkinsfile, optin/reporting/scripts/ci/build.sh, optin/reporting/scripts/ci/lint.sh, optin/reporting/scripts/ci/setup_lint.sh, optin/reporting/scripts/ci/test.sh
- Scripts and Jenkinsfile are added
- `productConfiguration.yaml` is updated
- Optin-reporting backend test script will be enabled when #76 is merged
- Badges will be updated before `init-reporting` is merged _in a separate PR_ (after node-watch badges is merged)
=> [optin/reporting] task: jenkins integration

nodewatch/monitoring/HeightChartBuilder.py, nodewatch/monitoring/NetworkConnector.py, nodewatch/monitoring/NetworkRepository.py, nodewatch/monitoring/VersionChartBuilder.py, nodewatch/monitoring/__init__.py, nodewatch/monitoring/chart_utils.py
Build lint fail.
- fix the lint issue such as indents and spacing
=> [nodewatch] task: fix lint error

.github/buildConfiguration.yaml, README.md, nodewatch/monitoring/HeightChartBuilder.py, nodewatch/monitoring/NetworkConnector.py, nodewatch/monitoring/NetworkRepository.py, nodewatch/monitoring/VersionChartBuilder.py, nodewatch/monitoring/__init__.py, nodewatch/monitoring/chart_utils.py, nodewatch/scripts/ci/setup_lint.sh, nodewatch/scripts/ci/test.sh
Missing build config in jenkins.
- added jenkis config.
- added lint badges
=> [nodewatch] task: add build config and badges

tools/vanity/.coveragerc, tools/vanity/tests/test_AddressGenerator.py, tools/vanity/tests/test_main.py, tools/vanity/vanity/AddressGenerator.py, tools/vanity/vanity/__main__.py
problem: code coverage numbers aren't being calculated correctly due to missing .coveragerc file
solution: add .coveragerc file in line with other python projects
add tests for __main__
=> [tools/vanity]: tools/vanity is missing .coveragerc file

explorer/nodewatch/nodewatch/__init__.py
problem: latest pylint fails with use-dict-literal
solution: remove the use of dict
=> [nodewatch] fix: linting failing with the latest pylint version

explorer/nodewatch/nodewatch/RoutesFacade.py, explorer/nodewatch/tests/test_RoutesFacade.py
problem: 0.6.101 was release but showed as red
solution: update nem 0.6.101 green since its the latest release 
https://nodewatch.symbol.tools/nem/nodes
=> [explorer/nodewatch] fix:make nem 0.6.101 green

explorer/nodewatch/nodewatch/RoutesFacade.py
* add latest catapult version 1.0.3.6
* restructure color shades
=> [explorer/nodewatch]: add latest Symbol version

connectors/python/symbolconnectors/connector/SymbolConnector.py, connectors/python/tests/connector/test_SymbolConnector.py
add:
- network_time
- account_links
=> [connectors/python]: port SymbolConnector functions required by shoestring

explorer/nodewatch/Jenkinsfile, faucet/authenticator/Jenkinsfile, faucet/backend/Jenkinsfile, faucet/frontend/Jenkinsfile, lightapi/python/Jenkinsfile, optin/puller/Jenkinsfile, optin/reporting/Jenkinsfile, tools/shoestring/Jenkinsfile, tools/vanity/Jenkinsfile
problem: Jenkinsfile structure change with ARM support.
solution: update Jenkinsfile to match the update parameter
=> [monorepo] fix: update Jenkinsfile

explorer/puller/client/BasicClient.py, explorer/puller/client/NemClient.py, explorer/puller/model/Exceptions.py, explorer/puller/tests/client/test_NemClient.py, explorer/puller/tests/test_data.py
new add nem client and unit test
=> [explorer/puller] task: add nem client

explorer/puller/dev_requirements.txt, explorer/puller/requirements.txt, explorer/puller/scripts/ci/lint.sh, explorer/puller/scripts/ci/setup_lint.sh, explorer/puller/scripts/ci/test.sh
this is the new sub repo
- added script/ci and python library requirement
=> [explorer/puller]: init explorer puller

faucet/frontend/components/common/FaucetForm/FaucetForm.spec.jsx, faucet/frontend/components/common/TextBox/TextBox.spec.jsx
- bot merged breaking change (userEvent) dependency causing the unit test to fail.
- fix the breaking change issue
=> [faucet/fronted] task: fix userEvent breaking change

faucet/frontend/components/nem/locales/en.json
=> [faucet/frontend] docs: patch description

faucet/backend/README.md
- readme info is outdated.
- update missing information in the readme.
=> [faucet/backend] docs: update readme

explorer/nodewatch/requirements.txt, explorer/puller/requirements.txt, faucet/frontend/package-lock.json, lightapi/python/requirements.txt, optin/puller/requirements.txt, optin/reporting/client/package-lock.json, optin/reporting/package-lock.json, tools/shoestring/requirements.txt
problem: Dependabot is failing to update dependenies due to invalid commit messages.
solution: update the dependenies manually
=> [monorepo]: update dependenies

faucet/frontend/package-lock.json, faucet/frontend/package.json
=> [faucet/frontend] build: bump version

explorer/rest/requirements.txt, explorer/rest/rest/__init__.py, explorer/rest/tests/test_rest.py
- The frontend UI was experiencing issues accessing the server due to missing CORS implementation.
- Implemented CORS to resolve the access issues.
=> [explorer/rest]: Implemented CORS

tools/shoestring/shoestring/wizard/TabbedView.py
problem: new invalid name with pylint 3
solution: disable invalid name since its related to prompt_toolkit
=> [tools/shoestring] fix: linting failing with pylint 3

.github/workflows/codeql-analysis.yaml
problem: CodeQl is not using the latest format
solution: update to the latest
=> [monorepo] fix: update CodeQL to the latest format

.github/buildConfiguration.yaml, snap/frontend/app/globals.css, snap/frontend/components/AccountBalance/AccountBalance.spec.jsx, snap/frontend/components/AccountBalance/index.jsx, snap/frontend/components/AccountInfo/AccountInfo.spec.jsx, snap/frontend/components/AccountInfo/index.jsx, snap/frontend/components/AssetList/AssetList.spec.jsx, snap/frontend/components/AssetList/index.jsx, snap/frontend/components/Dropdown/index.jsx, snap/frontend/components/Home/Home.spec.jsx, snap/frontend/components/Home/index.jsx, snap/frontend/components/LoadingScreen/index.jsx, snap/frontend/components/Navbar/Navbar.spec.jsx, snap/frontend/components/Navbar/index.jsx, snap/frontend/components/TransactionTable/TransactionTable.spec.jsx, snap/frontend/components/TransactionTable/index.jsx, snap/frontend/components/testHelper.js, snap/frontend/context/reducer.js, snap/frontend/public/copy-icon.svg, snap/frontend/public/finalized-icon.svg, snap/frontend/public/message-icon.svg, snap/frontend/public/receive-icon.svg, snap/frontend/public/send-icon.svg, snap/frontend/tailwind.config.js
- Missing profile screen components 
- Added components and unit test
- Navbar
- AccountInfo
- AssetList
- AccountBalance
- TransactionTable
- LoadingScreen
@Wayonb Added screenshot here.
=> [snap/frontend]: Added components for profile screen

snap/frontend/app/page.jsx, snap/frontend/components/ConnectMetamask/ConnectMetamask.spec.jsx, snap/frontend/components/ConnectMetamask/index.jsx, snap/frontend/hooks/useWalletInstallation.jsx, snap/frontend/hooks/useWalletInstallation.spec.jsx, snap/frontend/utils/dispatchUtils.js, snap/frontend/utils/dispatchUtils.spec.js
- Difficult to handle dispatch
- Added `dispatchUtils` to manage dispatch actions easily
=> [snap/frontend]: Added dispatch Utils

snap/frontend/components/AccountInfo/index.jsx, snap/frontend/components/Address/Address.spec.jsx, snap/frontend/components/Address/index.jsx
- The address could not be copied.
- Refactor it into address components.
- Allow the address to be copied when clicking the copy button.
=> [snap/frontend]: added address component

snap/backend/snap.manifest.json, snap/backend/src/index.js, snap/backend/src/services/symbolClient.js, snap/backend/src/utils/transactionUtils.js, snap/backend/test/index_spec.js, snap/backend/test/services/symbolClient_spec.js, snap/backend/test/utils/transactionUtils_spec.js, snap/frontend/app/page.spec.jsx, snap/frontend/components/Home/index.jsx, snap/frontend/components/TransactionTable/TransactionTable.spec.jsx, snap/frontend/components/TransactionTable/index.jsx, snap/frontend/config/index.js, snap/frontend/context/reducer.js, snap/frontend/package-lock.json, snap/frontend/package.json, snap/frontend/setupTests.js, snap/frontend/utils/dispatchUtils.js, snap/frontend/utils/dispatchUtils.spec.js, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- Backend service was not implemented.
- The container style of the transaction table was misaligned when transactions loaded.
- Added infinity scrolling to the transaction table.
- Fixed the container style issue in the transaction table.
- Implemented fetching account transactions in the snap factory.
- Added explorer URL configuration, allowing generation of explorer links in the transaction table.
- Replaced confirm/pending status with the transaction type name.
- The transaction table will initially fetch transactions from the selected address. When the user scrolls to the bottom, it will request more transactions. This will continue until the last page is reached, after which no more requests will be made.
=> [Snap/frontend]: Refactor transaction table, and implement backend service

snap/frontend/components/Home/Home.spec.jsx, snap/frontend/components/Home/index.jsx, snap/frontend/components/TransferModalBox/TransferModalBox.spec.jsx, snap/frontend/components/TransferModalBox/index.jsx
- The transfer transaction form is missing when clicking on the send button on the home page.
- Added transfer transaction form.
- Click on the **Send** button to pop up the modal box.
- Added form validation, such as Address (network check), mosaic amount, and message length.
- Handle mosaic selector logic, when the user clicks on "Add" mosaic, the options will be filtered (no duplicate).
Preview:
=> [snap/frontend]: Added transfer form component

snap/frontend/components/FeeMultiplier/FeeMultiplier.spec.jsx, snap/frontend/components/FeeMultiplier/index.jsx, snap/frontend/components/Home/Home.spec.jsx, snap/frontend/components/TransferModalBox/TransferModalBox.spec.jsx, snap/frontend/components/TransferModalBox/index.jsx, snap/frontend/package-lock.json, snap/frontend/setupTests.js, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- The fee multiplier option is missing in the transfer form.
- Query fee multiplier from snap state.
- Added fee multiplier frontend.
=> [snap/frontend]: Added fee multiplier component.

snap/backend/src/services/symbolClient.js, snap/backend/test/services/symbolClient_spec.js
- Missing endpoint to announce transaction.
- Added announce transaction endpoint
=> [snap/backend]: Added announce endpoint.

faucet/authenticator/src/controllers/index.js, faucet/authenticator/test/controllers/index_spec.js
- The user object doesn't have a Twitter profile URL.
- Query original dimension profile images, and added in profileImageUrl properties.
=> [faucet/authenticator]: Added profileImageUrl (original dimension).

faucet/authenticator/CHANGELOG.md, faucet/authenticator/package-lock.json, faucet/authenticator/package.json
- added profileImageUrl (original dimension) in user profile
=> [faucet/authenticator]: Release note 1.0.1

snap/frontend/components/FeeMultiplier/index.jsx, snap/frontend/components/TransferModalBox/TransferModalBox.spec.jsx, snap/frontend/components/TransferModalBox/index.jsx, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- missing send transaction action.
- Implement sign transfer transactions in the frontend component
- Added sign transfer transaction in helper and snap factory
=> [snap/frontend]: implement sign transaction in form

snap/backend/package-lock.json, snap/frontend/components/AccountListModalBox/AccountListModalBox.spec.jsx, snap/frontend/components/AccountListModalBox/index.jsx
- Account mosaic is not updated when switching to another address.
- Always query the latest mosaic balance as long as the user changes the address.
=> [snap/frontend]: Pulling latest account mosaic when changing account

snap/frontend/app/page.jsx, snap/frontend/app/page.spec.jsx, snap/frontend/components/TransactionTable/TransactionTable.spec.jsx, snap/frontend/components/TransactionTable/index.jsx, snap/frontend/components/TransferModalBox/TransferModalBox.spec.jsx, snap/frontend/components/TransferModalBox/index.jsx, snap/frontend/package-lock.json, snap/frontend/package.json, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- Duplicated invoke a snap method in the snap factory.
- extract the invoke method.
=> [snap/frontend]: Refactor on snap factory, extract invoke snap method

tools/shoestring/shoestring/lang/en/LC_MESSAGES/messages.po, tools/shoestring/shoestring/lang/ja/LC_MESSAGES/messages.po, tools/shoestring/shoestring/lang/messages.pot, tools/shoestring/shoestring/wizard/screens/node_settings.py, tools/shoestring/shoestring/wizard/screens/node_type.py, tools/shoestring/shoestring/wizard/setup_file_generator.py, tools/shoestring/tests/wizard/screens/test_node_settings.py, tools/shoestring/tests/wizard/test_setup_file_generator.py
problem: There is no option to deploy the Light node from the wizard
solution: add a radio button for the Light node
=> [tools/shoestring]: add light node option to wizard

bridge/bridge/NetworkFacadeLoader.py, bridge/bridge/NetworkUtils.py, bridge/bridge/db/WrapRequestDatabase.py, bridge/bridge/ethereum/EthereumAdapters.py, bridge/bridge/ethereum/EthereumConnector.py, bridge/bridge/ethereum/EthereumNetworkFacade.py, bridge/bridge/ethereum/EthereumUtils.py, bridge/bridge/ethereum/RpcUtils.py, bridge/bridge/nem/NemNetworkFacade.py, bridge/bridge/symbol/SymbolNetworkFacade.py, bridge/tests/db/test_WrapRequestDatabase.py, bridge/tests/ethereum/test_EthereumAdapters.py, bridge/tests/ethereum/test_EthereumConnector.py, bridge/tests/ethereum/test_EthereumNetworkFacade.py, bridge/tests/ethereum/test_EthereumUtils.py, bridge/tests/ethereum/test_RpcUtils.py, bridge/tests/nem/test_NemNetworkFacade.py, bridge/tests/symbol/test_SymbolNetworkFacade.py, bridge/tests/test/MockEthereumServer.py, bridge/tests/test_NetworkFacadeLoader.py, lightapi/python/tests/connector/test_NemConnector.py, lightapi/python/tests/connector/test_SymbolConnector.py
problem: Ethereum support needs to be added
solution: add support for Ethereum as a wrapped network in all workflows
=> [bridge]: add Ethereum integration for worklows

bridge/bridge/NetworkUtils.py, bridge/bridge/api/Validators.py, bridge/bridge/api/__init__.py, bridge/bridge/ethereum/EthereumNetworkFacade.py, bridge/tests/api/test_Validators.py, bridge/tests/api/test_app.py, bridge/tests/ethereum/test_EthereumNetworkFacade.py, bridge/tests/test_NetworkFacadeLoader.py, bridge/tests/test_NetworkUtils.py
fix bugs and enhance API behavior
=> [bridge]: second round of API fixes and improvements

bridge/bridge/WorkflowUtils.py, bridge/bridge/api/__init__.py, bridge/bridge/models/BridgeConfiguration.py, bridge/bridge/models/Constants.py, bridge/tests/models/test_BridgeConfiguration.py, bridge/tests/resources/sample.config.properties, bridge/tests/test_WorkflowUtils.py, bridge/workflows/check_finalized_transactions.py, bridge/workflows/download_balance_changes.py, bridge/workflows/download_wrap_requests.py, bridge/workflows/main_impl.py, bridge/workflows/send_payouts.py
problem: conversion rate is dynamically calculated based on balances
solution: add strategy that fixes conversion rate at 1:1
=> [bridge]: add support for wrapped (1:1) mode

bridge/README.md
Problem: README for Bridge project is empty.
Solution: Added Bridge README content.
=> [bridge] Added initial README for bridge project

explorer/puller/puller/db/DatabaseConnection.py, explorer/puller/puller/db/NemDatabase.py, explorer/puller/tests/db/test_DatabaseConnection.py, explorer/puller/tests/db/test_NemDatabase.py
Problem: working on nem puller, missing database connection.
Solution: Added db connection and nem database (blocks tables)
=> [explorer/puller] feat: init database connection and blocks table
