optin/reporting/client/package.json, optin/reporting/client/src/components/Table/Table.jsx, optin/reporting/client/src/pages/Home/Home.jsx, optin/reporting/client/src/pages/Home/Home.scss, optin/reporting/client/src/styles/globals.scss
- The table body goes off of the viewport;
- Changed the table width to match the width of a viewport;
- Changed the table height to fill the rest of remaining space (`flex: 1`);
- Added scrollbars to the table body instead of the viewport;
- Changed infinite-loader to trigger when the end of the table is reached. Removed 3rd party dependency;
- Added sticky table header;
=> [optin/reporting/client] fix: table body overflow

explorer/nodewatch/README.md, explorer/nodewatch/nodewatch/NetworkRepository.py, explorer/nodewatch/requirements.txt
1. Update the nodewatch to use symbol-sdk-python 3.0.3
2. Update readme to run nodewatch
=> [nodewatch] fix: update to python sdk 3

.gitlintmodules, README.md
- nodewatch should belong to `explorer` folder
- move `nodewatch` to `explorer`
- update readme and build config path
=> [explorer/nodewatch] task: fix nodewatch layout issue

optin/reporting/Jenkinsfile
The manual private release build(in Jenkins) cannot produce the expected image. `dockerImageName` field in the Jenkinsfile needs to be set explicitly.
* `dockerImageName` is set to `symbolplatform/optin-reporting`
* minimumCodeCoverage is now increased to 95%
=> [optin/reporting] fix: set docker image name and increased coverage to 95 in jenkinsfile

explorer/nodewatch/nodewatch/VersionChartBuilder.py, optin/reporting/client/package-lock.json, optin/reporting/client/package.json, optin/reporting/package-lock.json, optin/reporting/package.json, tools/vanity/tests/test_AddressGenerator.py, tools/vanity/vanity/AddressGenerator.py
With the latest pylint version, new issues were found and fix
1. nodewatch/VersionChartBuilder.py:65:16: R1728: Consider using a generator instead
2. vanity/AddressGenerator.py:43:46: W0130: Duplicate value 0 in set (duplicate-value)
=> [dependency] fix: linting failures due to pylint update

.github/codecov.yaml
problem: code coverage checks will fail due to a small drop in percentage.
solution: Allow a drop of up to 1% in code coverage.
=> [monorepo] fix: add threshold for code coverage drop

.github/dependabot.yaml, optin/reporting/client/package-lock.json, optin/reporting/client/package.json, optin/reporting/client/src/pages/Completed/Completed.test.js, optin/reporting/client/src/pages/Requests/Requests.test.js, optin/reporting/package-lock.json, optin/reporting/package.json, optin/reporting/test/models/completed.spec.js
problem: new release for sqlite3 and testing-library cause failure in tests 
solution: testing-library userevent functions are now async so added await
the nemSource is now a string instead of object
also disable dependabot major version updates for optin projects
=> [optin/reporting] fix: failing tests on dependency update

.github/buildConfiguration.yaml
problem: nightly build properties was in the code.
solution: move nightly job to the buildconfiguration file.
=> [monorepo] fix: move nightly builds to bulid configuration file

explorer/nodewatch/nodewatch/NetworkRepository.py, explorer/nodewatch/nodewatch/RoutesFacade.py, explorer/nodewatch/tests/resources/symbol_nodes.json, explorer/nodewatch/tests/test_NetworkRepository.py, explorer/nodewatch/tests/test_RoutesFacade.py, explorer/nodewatch/tests/test_app.py
problem: nodewatch should estimate network wide finalized height
solution: add 'finalizedHeight' to /api/xyz/height apis
=> [explorer/nodewatch]: estimate network wide finalized heights

optin/reporting/client/src/pages/Completed/Completed.jsx, optin/reporting/client/src/pages/Requests/Requests.jsx
problem: new rules were added to default.eslintrc for sorted imports
solution: sort the failing imports correctly
=> [optin/reporting/client] fix: lint failure due to incorrectly sorted imports

.gitlintmodules, connectors/python/pyproject.toml
problem: in preparation for release need to bump version.
solution: bump the  python connectors to 0.0.2 for release
=> [connectors/python] fix: bump python connectors version to 0.0.2

README.md
problem: Jenkins multibranch jobs were updated to use the full folder name instead of just the last folder
solution: update the README to use the updated multibranch job name
=> [monorepo] fix: update read to match new job names

lightapi/python/symbollightapi/connector/SymbolPeerConnector.py, lightapi/python/symbollightapi/model/PacketHeader.py, lightapi/python/tests/connector/test_SymbolPeerConnector.py
API node is not required for this information, so make it possible to retrieve from PEER node
=> [lightapi/python]: add SymbolPeerConnector.network_time

lightapi/python/symbollightapi/connector/SymbolPeerConnector.py, lightapi/python/tests/connector/test_SymbolPeerConnector.py
when there multiple component exceptions within open_connection, they are wrapped in a single OSError
=> [lightapi/python]: handle OSError raised by open_connection

.github/dependabot.yaml
problem: there are two entries for github-action in the dependabot.yaml file
solution: remove the last entry for github-action
=> [monorepo] fix: remove duplicate ecosystem entry

faucet/authenticator/Jenkinsfile, faucet/authenticator/package-lock.json, faucet/authenticator/package.json
- lint, test, and coverage status didn't show up in the readme.
- fix the wrong jenkins package id in readme
=>  [faucet/authenticator]: fix readme packageId

faucet/frontend/components/common/FaucetForm/index.jsx, faucet/frontend/components/common/TwitterSignIn/index.jsx, faucet/frontend/package-lock.json, faucet/frontend/package.json
- jwt token causes a dependencies security alert.
- patched to the latest version
=> [faucet/fronted]: patch jwt token dependencies to 9.0.0

faucet/frontend/Dockerfile, faucet/frontend/next.config.js, faucet/frontend/scripts/docker/startup.sh
- Faucet frontend docker image is not able to assign dynamic env params, which it needs to separate build different images to run NEM / Symbol website.
- instead of building a website inside the images, I move the build logic in the docker run time.
- the docker run will accept env params, and build different website
```
docker run -e NEXT_PUBLIC_BUILD_TARGET="nem" \
-e NEXT_PUBLIC_META_TITLE="The XEM Faucet" \
-e NEXT_PUBLIC_META_DESCRIPTION="NEM Faucet" \
-e NEXT_PUBLIC_AUTH_URL=https://faucet-auth.url.io \
-e NEXT_PUBLIC_BACKEND_URL=https://faucet-backend.url.io \
-e NEXT_PUBLIC_AES_SECRET="secret" \
-p 3000:3000 \
--name nem-frontend \
frontend:latest
```
=> [faucet/fronted]: fix dynamic docker run on image

faucet/backend/test/server_spec.js
- Randomly hit the error in the unit test, I believe it should cause by a race condition problem.
https://jenkins.symboldev.com/blue/organizations/jenkins/Symbol%2Fgenerated%2Fproduct%2Ffaucet-backend/detail/dev/51/pipeline/
- added async/await to ensure table is created before run the test
=> [Faucet/backend] task: fix race test

tools/shoestring/pyproject.toml, tools/shoestring/shoestring/healthagents/rest_https_certificate.py, tools/shoestring/shoestring/internal/OpensslExecutor.py, tools/shoestring/shoestring/internal/PackageResolver.py, tools/shoestring/tests/commands/test_renew_certificates.py, tools/shoestring/tests/commands/test_setup.py, tools/shoestring/tests/healthagents/test_rest_https_certificate.py, tools/shoestring/tests/internal/test_Preparer.py
problem: Ubuntu 20.04 ships with an older version of Python and Openssl which caused failures when running shoestring.
1. Openssl 1.1.x output is different from Openssl 3.x
2. Python 3.8, ``shutil.move`` does not support a path object.
solution: 1. Normalize the Openssl output so it works for both version
2. Python 3.8 convert the path objects to string.
=> [tools/shoestring] fix: add support for Ubuntu 20.04

tools/shoestring/shoestring/healthagents/rest_https_certificate.py
Update to use ``openssl storeutl`` to parse all certificates instead of ``openssl x509`` which only returns information for the first.
``openssl storeutl`` will fail if the input is not a valid pem, extract the certificate information from the output of ``openssl s_client``.
=> [tools/shoestring]: allow collect of multiple certificates date

optin/puller/tests/client/test_NemClient.py
problem: linting is failing due to missing space after colon(:)
solution: add space after colon(:)
=> [optin/puller]: add space after colon

lightapi/python/scripts/ci/build.sh, lightapi/python/scripts/ci/publish.sh
problem: lightapi does not use poetry for publishing its artifact
solution: create a custom script for publishing
=> [lightapi/python]: add custom publishing for lightapi

lightapi/python/cffi_src/openssl_build.py
problem: OpenSSL library names start with `lib` which caused MSVC to fail to find the file during linking.
solution: For Windows builds, prepend `lib` to the OpenSSL library names.
=> [lightapi/python] fix: cffi fails to build on Windows

.github/dependabot.yaml
problem: grouping Dependabot PRs can lead to conflicts in GitHub Action.
solution: enable grouping in Dependabot will group at the project level and resolve conflicts.
=> [monorepo]: enable dependabot group update for each project

explorer/rest/rest/__init__.py, explorer/rest/rest/db/NemDatabase.py, explorer/rest/rest/facade/NemRestFacade.py, explorer/rest/tests/db/test_NemDatabase.py, explorer/rest/tests/facade/test_NemRestFacade.py, explorer/rest/tests/test/DatabaseTestUtils.py, explorer/rest/tests/test_rest.py
- Currently, blocks are returned in ASC order by height, which is not user-friendly, In the explorer, we need the blocks to be sorted by default in DESC order of height.
- Added a sort filter to the blocks list.
- Set the default sorting of block height to DESC order.
=> [explorer/rest]: added sort block by height filter in blocks endpoints

.github/buildConfiguration.yaml, .github/jenkinsfile/weeklyBuild.groovy, lightapi/python/Jenkinsfile, tools/shoestring/Jenkinsfile
problem: Lightapi and Shoestring are not able to run tests in different Python environments
solution: Lightapi has a Windows and Python base and the latest weekly runs
Shoestring has a Python base and the latest weekly runs
=> [monorepo] task: enable weekly build for Lightapi and Shoestring

tools/shoestring/shoestring/internal/NodeFeatures.py, tools/shoestring/shoestring/internal/ShoestringConfiguration.py, tools/shoestring/shoestring/wizard/setup_file_generator.py, tools/shoestring/tests/internal/test_NodeFeatures.py, tools/shoestring/tests/test/ConfigurationTestUtils.py
problem: python 3.11 changed Enum.__str__ to use int.__str__
solution: add NodeFeatures.to_formatted_string and use as appropriate
=> [tools/shoestring]: update shoestring to support python 3.11

.gitlintmodules
- Jenkins verify commit failed
- patch missing name inside gitlintmodules
=> [explorer/rest]: patch missing project name inside gitlintmodules

faucet/frontend/components/common/FaucetForm/FaucetForm.spec.jsx, faucet/frontend/components/common/FaucetForm/index.jsx, faucet/frontend/components/nem/locales/en.json, faucet/frontend/components/symbol/locales/en.json
- the message of `notification_error_unqualified_twitter_account` is not clear enough.
- update the requirement message in the error notification
=> [faucet/frontend]: enhancement of error message

lightapi/python/Jenkinsfile, tools/shoestring/Jenkinsfile
problem: tests are not run on Fedora
solution: add weekly jobs on Fedora
=> [lightapi, shoestring] fix: add fedora weekly jobs for lightapi and shoestring

tools/shoestring/shoestring/internal/CertificateFactory.py, tools/shoestring/tests/internal/test_CertificateFactory.py, tools/shoestring/tests/internal/test_OpensslExecutor.py, tools/shoestring/tests/test/CertificateTestUtils.py
* allow openssl version 3.2.x
* ignore unimportant whitespace in openssl output
* generate x509 v3 certificates
=> [tools/shoestring]: fixes for openssl 3.2.0 support

tools/shoestring/shoestring/commands/health.py, tools/shoestring/shoestring/healthagents/peer_api.py, tools/shoestring/shoestring/healthagents/rest_https_certificate.py, tools/shoestring/tests/commands/test_health.py, tools/shoestring/tests/healthagents/test_peer_api.py, tools/shoestring/tests/healthagents/test_rest_https_certificate.py, tools/shoestring/tests/internal/test_ConfigurationManager.py
problem: health agent is accessing wrong property from context
solution: fix access and update agents to use domainname when specified
=> [tools/shoestring]: fix health check failure on nodes with https REST

.github/jenkinsfile/controller.groovy
problem: currently all jobs are run for each checkin
solution: enable controller job which will only run the
required jobs for the commit.
=> [monorepo]: enable controller job for CI

lightapi/python/symbollightapi/connector/BasicConnector.py, lightapi/python/tests/connector/test_BasicConnector.py
problem: only HTTP statuses 200 and 404 are treated as non-error
solution: treate all statuses less than 400 and 404 as non-error
fixes: #867
=> [lightapi/python]: treat all HTTP statuses less than 400 as success

snap/frontend/app/page.jsx, snap/frontend/components/ConnectMetamask/ConnectMetamask.spec.jsx, snap/frontend/components/ConnectMetamask/index.jsx, snap/frontend/components/Home/Home.spec.jsx, snap/frontend/components/Home/index.jsx, snap/frontend/config/index.js, snap/frontend/context/index.js, snap/frontend/context/reducer.js, snap/frontend/context/store.js, snap/frontend/hooks/useWalletInstallation.jsx, snap/frontend/hooks/useWalletInstallation.spec.jsx, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- wallet connected to snap is not implemented.
- added snap utils: which are used for request active to metamask snap.
- added hook: to check metamask installation status in the browser.
- added context (state, reducer)
- DetectMetamask modal will pop up if the browser doesn't install metamask.
- ConnectMetamask modal will pop up if symbol snap doesn't install in metamask.
- Click on the Connect button, and Metamask should pop up and ask you to install Symbol Snap. 
note: If you like to test on a browser, it required to install [Flask](https://docs.metamask.io/snaps/get-started/install-flask/)
=> [snap/frontend]: implement wallet connection

tools/vanity/scripts/ci/test_examples.sh, tools/vanity/vanity/__main__.py
```
problem: when specified, max-offset argument is treated as string
solution: coerce max-offset to int
add a few test examples to detect future regressions
```
=> [tools/vanity]: max-offset argument is not coerced to int

tools/vanity/scripts/ci/test_examples.sh
problem: vanity example is failing due to TMPDIR is undefine on Ubuntu
solution: use the mktemp to generate a temp file name
=> [tools/vanity] fix: TMPDIR is not defined in Ubuntu

snap/backend/snap.manifest.json, snap/backend/src/config.js, snap/backend/src/index.js, snap/backend/src/services/statisticsClient.js, snap/backend/src/utils/fetchUtils.js, snap/backend/src/utils/networkUtils.js, snap/backend/test/index_spec.js, snap/backend/test/services/statisticsClient_spec.js, snap/backend/test/utils/fetchUtils_spec.js, snap/backend/test/utils/networkUtils_spec.js, snap/frontend/components/Navbar/Navbar.spec.jsx, snap/frontend/components/Navbar/index.jsx, snap/frontend/context/reducer.js, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- Implement navbar network dropdown 
- Backend
- Added fetch data utils.
- Added statistic client which is used to query network nodes
- Added switch network method
- Added `getNetowork` and `switchNetwork`, refactor snap onRpcRequest,
- Frontend 
- Implement on click network dropdown switch network
=> [Snap]: Implementation of navbar dropdown (network)

snap/frontend/app/page.spec.jsx, snap/frontend/components/Home/Home.spec.jsx, snap/frontend/components/Home/index.jsx, snap/frontend/components/Navbar/Navbar.spec.jsx, snap/frontend/components/Navbar/index.jsx, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
The page didn't load state when the page was first loaded.
- Call the `initialSnap` method when the page loads and snap is installed.
- Added loading status when waiting for initialSnap return.
=> [snap/frontend]: implement initial snap

snap/backend/package-lock.json, snap/backend/package.json, snap/backend/snap.manifest.json, snap/backend/src/utils/accountUtils.js, snap/backend/test/utils/accountUtils_spec.js
- To generate a Symbol keypair, we need to derive the keypair from the metamask snap.
- Added `deriveKeyPair` to derive keypair from metamask snap.
- It supports coin-type: 4343 (mainnet) and 1 (testnet)
=> [snap/backend]: Added derive key pair from metamask

snap/frontend/components/AccountInfo/AccountInfo.spec.jsx, snap/frontend/components/AccountInfo/index.jsx, snap/frontend/components/AccountListModalBox/AccountListModalBox.spec.jsx, snap/frontend/components/AccountListModalBox/index.jsx, snap/frontend/components/Home/Home.spec.jsx, snap/frontend/components/Input/index.jsx, snap/frontend/components/testHelper.js, snap/frontend/context/reducer.js, snap/frontend/utils/dispatchUtils.js, snap/frontend/utils/dispatchUtils.spec.js, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js
- Display all Symbol accounts from the snap.
- Added account list modal box
- click on the profile image, and the modal box pops up.
=> [snap/frontend]: Added account list component

snap/backend/src/utils/accountUtils.js, snap/backend/test/utils/accountUtils_spec.js, snap/frontend/components/AccountCreateModalBox/AccountCreateModalBox.spec.jsx, snap/frontend/components/AccountCreateModalBox/index.jsx, snap/frontend/components/AccountInfo/index.jsx, snap/frontend/components/AccountListModalBox/AccountListModalBox.spec.jsx, snap/frontend/components/AccountListModalBox/index.jsx, snap/frontend/components/testHelper.js, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- it does not allow create multiple accounts
- Added AccountCreateModalBox components containing an input box for the wallet name.
- When a new account is created, it will update the account list and selected account state.
- Validation of wallet name
Validation Input box
Success created new account
=> [snap/frontend]: create multiple account

snap/backend/snap.manifest.json, snap/backend/src/config.js, snap/backend/src/index.js, snap/backend/src/services/cryptocompareClient.js, snap/backend/src/utils/priceUtils.js, snap/backend/test/index_spec.js, snap/backend/test/services/cryptocompareClient_spec.js, snap/backend/test/utils/priceUtils_spec.js, snap/frontend/app/page.spec.jsx, snap/frontend/components/AccountBalance/AccountBalance.spec.jsx, snap/frontend/components/AccountBalance/index.jsx, snap/frontend/components/Home/Home.spec.jsx, snap/frontend/components/Home/index.jsx, snap/frontend/components/Navbar/Navbar.spec.jsx, snap/frontend/components/Navbar/index.jsx, snap/frontend/context/reducer.js, snap/frontend/utils/dispatchUtils.js, snap/frontend/utils/dispatchUtils.spec.js, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- Currency in the navbar has not been implemented.
- Added `cryptoCompareClient` to fetch XYM price in USD and JPY.
- Added `priceUtils`
- `getPrice` fetch the price from `cryptoCompareClient`.
- `getCurrencyPrice` return price by given symbol (usd/jpy).
- Added `currency` params in `setupSnap` method.
- Added cronjob every minute will fetch the price.
- Implement in frontend Navbar component, which the user can switch between USD / JPY
- In the backend, every minute (cronjob from snap) will request the latest price from `cryptoCompareClient` and store it as a cache.
- Frontend will access the currency price from the backend cache.
=> [snap]: Implement currecny (USD/JPY) support in navbar

snap/backend/snap.manifest.json, snap/backend/src/index.js, snap/backend/src/services/symbolClient.js, snap/backend/src/utils/accountUtils.js, snap/backend/src/utils/mosaicUtils.js, snap/backend/src/utils/networkUtils.js, snap/backend/test/.eslintrc, snap/backend/test/index_spec.js, snap/backend/test/services/symbolClient_spec.js, snap/backend/test/utils/accountUtils_spec.js, snap/backend/test/utils/mosaicUtils_spec.js, snap/backend/test/utils/networkUtils_spec.js, snap/frontend/app/page.spec.jsx, snap/frontend/components/AccountBalance/AccountBalance.spec.jsx, snap/frontend/components/AccountBalance/index.jsx, snap/frontend/components/Home/Home.spec.jsx, snap/frontend/components/Home/index.jsx, snap/frontend/components/Navbar/Navbar.spec.jsx, snap/frontend/components/Navbar/index.jsx, snap/frontend/components/testHelper.js, snap/frontend/context/reducer.js, snap/frontend/utils/dispatchUtils.js, snap/frontend/utils/dispatchUtils.spec.js, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- The XYM balance was not being fetched from the network.
- Added a SymbolClient service to query the REST API.
- Added `currencyMoasicId` properties in the snap network state.
- Added `mosaicInfo` state to store all mosaic information as a cache, reducing the number of queries and making it easier to format the mosaic balance.
- Implemented querying of the account balance when create / import actions are triggered.
- Implemented querying of the first account balance when visiting the wallet. Subsequent updates of all accounts will happen in the background for a better user experience.
- Implemented these changes in the frontend account balance components.
=> [Snap]: fetch XYM mosaic balance and display in account balance components

snap/backend/snap.manifest.json, snap/backend/src/index.js, snap/backend/src/services/symbolClient.js, snap/backend/src/utils/transactionUtils.js, snap/backend/test/index_spec.js, snap/backend/test/services/symbolClient_spec.js, snap/backend/test/utils/transactionUtils_spec.js
- The fee multiplier is missing; we will use it to calculate the transaction fee.
- Added fee multiplier endpoint
- Extract slow, average, and fast multiplier
- Added fetch multiplier in onCronjob
=> [snap/backend]: Added fee multipler 

snap/backend/package-lock.json, snap/backend/package.json, snap/backend/snap.manifest.json, snap/backend/src/index.js, snap/backend/src/services/symbolClient.js, snap/backend/src/utils/transactionUtils.js, snap/backend/test/index_spec.js, snap/backend/test/services/symbolClient_spec.js, snap/backend/test/utils/transactionUtils_spec.js, snap/frontend/app/page.spec.jsx, snap/frontend/components/Home/index.jsx, snap/frontend/components/TransactionTable/TransactionTable.spec.jsx, snap/frontend/components/TransactionTable/index.jsx, snap/frontend/config/index.js, snap/frontend/context/reducer.js, snap/frontend/package-lock.json, snap/frontend/package.json, snap/frontend/setupTests.js, snap/frontend/utils/dispatchUtils.js, snap/frontend/utils/dispatchUtils.spec.js, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- Missing implementation transaction utils and RPC.
- Added `fetchAccountTransactions` to the RPC request.
- Added `fetchAccountTransactions` in `transactionUtils` to query account transactions, and request inner transactions if there is an aggregate transaction.
- Added transaction formatting and converted all inner transactions to a flat structure.
=> [snap/backend]: Added transaction utils and rpc.

snap/backend/snap.manifest.json, snap/backend/src/services/symbolClient.js, snap/backend/src/utils/mosaicUtils.js, snap/backend/test/services/symbolClient_spec.js, snap/backend/test/utils/mosaicUtils_spec.js, snap/frontend/components/AssetList/AssetList.spec.jsx, snap/frontend/components/AssetList/index.jsx, snap/frontend/utils/helper.js
- Mosaic didn't have a namespace name.
- Added mosaic namespace name query by mosaic id.
- Implement fetch mosaic namespace while fetching mosaic info.
- Implement selected account mosaic in the asset list components.
asset list
=> [Snap]: Process mosaic's namespace name in asset list

snap/frontend/config/index.js
- Missing `NEXT_PUBLIC_` naming in env config
- Added `NEXT_PUBLIC_` naming.
=> [snap/backend]: Fix config naming in env

snap/frontend/app/page.spec.jsx, snap/frontend/components/FeeMultiplier/index.jsx, snap/frontend/components/Home/Home.spec.jsx, snap/frontend/components/TransactionTable/TransactionTable.spec.jsx, snap/frontend/components/TransactionTable/index.jsx, snap/frontend/config/index.js, snap/frontend/context/reducer.js, snap/frontend/utils/dispatchUtils.js, snap/frontend/utils/dispatchUtils.spec.js, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js, snap/frontend/utils/webSocketClient.js, snap/frontend/utils/webSocketClient.spec.js
- We need a WebSocket implementation to improve the wallet's user experience.
- Added WebSocket client.
- Added listenConfrimTransaction method listener.
- Implement web socket in the `helper.setupSnap` and `open()` socket when the network changes.
- Store socket in context state,
- Implementation of listenConfrimTransaction in the transaction table component.
=> [snap/frontend]: WS implementation

snap/backend/snap.manifest.json, snap/backend/src/utils/transactionUtils.js, snap/backend/test/utils/transactionUtils_spec.js, snap/frontend/app/page.spec.jsx, snap/frontend/components/AccountListModalBox/AccountListModalBox.spec.jsx, snap/frontend/components/AccountListModalBox/index.jsx, snap/frontend/components/TransactionTable/TransactionTable.spec.jsx, snap/frontend/components/TransactionTable/index.jsx, snap/frontend/config/index.js, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js, snap/frontend/utils/webSocketClient.js, snap/frontend/utils/webSocketClient.spec.js
- Missing unconfirmed transaction display in table.
- Added unconfirmed transaction listener in WebSocket.
- Added transaction group into `fetchAccountTransactions` method param.
- Added `updateUnconfirmedTransactions` in helper, which updates unconfirmed transactions in the state.
- Implement unconfirmed transactions in transaction table component.
=> [snap]: Implemented unconfirmed transactions

snap/frontend/components/AssetList/index.jsx, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js
- An error occurs when the user creates or imports an account with an existing mosaic, and the mosaic info in the snap state is not current.
- Refactor AssetList component, join `renderMosaicNameOrId` and `renderMosaicDetails` method in `renderMosaicDetailsWithName` method
- Query the latest mosaic Info after creating / import the account
=> [snap/frontend]: fix mosaic info is not load correctly.

snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js
- After approving the transactions, the transfer transaction modal box didn't close, the reason is that after signing the transaction, it didn't return the transaction hash.
- Return transaction hash after signing the transaction in helper.
=> [snap/frontend]: bug fix return transaction hash

snap/backend/src/index.js, snap/backend/src/utils/accountUtils.js, snap/backend/test/index_spec.js, snap/backend/test/utils/accountUtils_spec.js, snap/frontend/components/AssetList/AssetList.spec.jsx, snap/frontend/components/AssetList/index.jsx, snap/frontend/components/FeeMultiplier/FeeMultiplier.spec.jsx, snap/frontend/components/FeeMultiplier/index.jsx, snap/frontend/components/Home/Home.spec.jsx, snap/frontend/components/TransferModalBox/TransferModalBox.spec.jsx, snap/frontend/components/TransferModalBox/index.jsx, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- For better validation transaction fees, it should have fee calculation and keep updated when the user inputs some data such as a message.
- Added fee calculation, it displays fees in the transfer transaction form.
- Fees validation to ensure the account has enough balance to do transactions.
- Refactor `signTransferTransaction` method, and replace `feeMultiplierType` with `fees` because the calculation is done by frontend.
=> [Snap]: Apply live transaction fees calculator.

snap/backend/src/utils/accountUtils.js, snap/backend/test/utils/accountUtils_spec.js
- Users cannot import the same private key in different networks.
- Validate filter private key and network.
=> [snap/backend]: bug fix filter account private key and network

snap/backend/src/index.js, snap/backend/test/index_spec.js, snap/frontend/components/AssetList/AssetList.spec.jsx, snap/frontend/components/AssetList/index.jsx
- The asset list appears empty when the account doesn't have a mosaic.
- Added a currency mosaic to the asset list with an amount of 0 if the account lacks a currency mosaic.
- Query currency mosaic info when during the `initial setup`
- Added currency mosaic in asset list, if user account lacks of currency mosaic.
=> [Snap]: Add currecy mosaic in asset list as default.

snap/backend/src/index.js, snap/backend/src/utils/accountUtils.js, snap/backend/test/index_spec.js, snap/backend/test/utils/accountUtils_spec.js, snap/frontend/components/AccountListModalBox/AccountListModalBox.spec.jsx, snap/frontend/components/AccountListModalBox/index.jsx, snap/frontend/components/AccountRenameModalBox/AccountRenameModalBox.spec.jsx, snap/frontend/components/AccountRenameModalBox/index.jsx, snap/frontend/components/AssetList/AssetList.spec.jsx, snap/frontend/context/reducer.js, snap/frontend/context/reducer.spec.js, snap/frontend/utils/dispatchUtils.js, snap/frontend/utils/dispatchUtils.spec.js, snap/frontend/utils/helper.js, snap/frontend/utils/helper.spec.js, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- Account label unable to update.
- Implemented an updated account label in the Snap backend.
- Added rename account modal box component.
- Implemented renaming the modal box in the account list components.
=> [Snap]: Rename account label

.gitignore, tools/shoestring/README.md, tools/shoestring/shoestring/commands/setup.py, tools/shoestring/shoestring/internal/ConfigurationManager.py, tools/shoestring/shoestring/internal/Preparer.py, tools/shoestring/shoestring/lang/en/LC_MESSAGES/messages.po, tools/shoestring/shoestring/lang/ja/LC_MESSAGES/messages.po, tools/shoestring/shoestring/lang/messages.pot, tools/shoestring/shoestring/wizard/ShoestringOperation.py, tools/shoestring/shoestring/wizard/setup_file_generator.py, tools/shoestring/shoestring/wizard/shoestring_dispatcher.py, tools/shoestring/tests/commands/test_setup.py, tools/shoestring/tests/internal/test_ConfigurationManager.py, tools/shoestring/tests/internal/test_Preparer.py, tools/shoestring/tests/wizard/test_ShoestringOperation.py, tools/shoestring/tests/wizard/test_setup_file_generator.py, tools/shoestring/tests/wizard/test_shoestring_dispatcher.py
problem: shoestring only allows user to specify nodeMetadata property of rest.config
solution: allow user to provide differential config file that overrides defaults (similar to REST native support)
issue: #1090
=> [tools/shoestring]: add support for advanced customization of rest.json

snap/frontend/app/page.jsx, snap/frontend/app/page.spec.jsx, snap/frontend/components/TransactionTable/TransactionTable.spec.jsx, snap/frontend/components/TransactionTable/index.jsx, snap/frontend/components/TransferModalBox/TransferModalBox.spec.jsx, snap/frontend/components/TransferModalBox/index.jsx, snap/frontend/package-lock.json, snap/frontend/package.json, snap/frontend/utils/snap.js, snap/frontend/utils/snap.spec.js
- All the errors will be thrown in console logs (browser), and adding a toast notification, will improve user experience.
- Added react-toastify library.
- Handle error messages from the snap factory.
- Handle successful messages: detect for announce/pending/confirmed transactions
=> [snap/frontend]: Added react-toastify (toast)

explorer/nodewatch/nodewatch/NetworkRepository.py, explorer/nodewatch/nodewatch/RoutesFacade.py, explorer/rest/rest/model/Block.py, lightapi/python/symbollightapi/model/NodeInfo.py, tools/shoestring/shoestring/wizard/ShoestringOperation.py, tools/shoestring/shoestring/wizard/ValidatingTextBox.py, tools/shoestring/shoestring/wizard/screens/harvesting.py, tools/shoestring/tests/healthagents/test_peer_certificate.py
[explorer/nodewatch]: disable too many positional arguments
problem: latest pylint add too many positional arguments
solution: disable too many positional arguments
[tools/shoestring]: disable too many positional arguments
problem: latest pylint add too many positional arguments
solution: disable too many positional arguments
[lightapi/python]: disable too many positional arguments
problem: latest pylint add too many positional arguments
solution: disable too many positional arguments
[explorer/rest]: disable too many positional arguments
problem: latest pylint add too many positional arguments
solution: disable too many positional argument
=> [lint]: pylint 3.3.x introduce too many positional arguments

tools/shoestring/requirements.txt, tools/shoestring/tests/healthagents/test_websockets.py
problem: serve() moved to the asyncio.server
solution: update import to use new path
=> [tools/shoestring]: add support for websockets 14

explorer/nodewatch/nodewatch/RoutesFacade.py, explorer/nodewatch/tests/test_RoutesFacade.py
problem: nodewatch does not show the latest version as green.
plus incompatible catapult are not marked as red.
solution: update nodewatch to show the correct colors
=> [explorer/nodewatch] fix: update the catapult compatible matrix

tools/shoestring/README.md, tools/shoestring/shoestring/commands/upgrade.py, tools/shoestring/shoestring/internal/Preparer.py, tools/shoestring/shoestring/startup/startRecovery.sh, tools/shoestring/shoestring/templates/docker-compose-dual.yaml, tools/shoestring/shoestring/templates/docker-compose-peer.yaml, tools/shoestring/tests/commands/test_setup.py, tools/shoestring/tests/commands/test_upgrade.py, tools/shoestring/tests/internal/test_Preparer.py
problem: There is no way to recover from lock files in the data folder
solution: create a docker-compose-recovery.yaml which will run the recovery tool
=> [tools/shoestring]: add recovery tool

lightapi/python/symbollightapi/connector/SymbolPeerConnector.py
problem: RFC5280 validation is enabled by default in Python 3.13 which causes cert validation failure.
solution: disable RFC5280 validation since our certs are X509 compliant and RFC5280 is not needed.
=> [lightapi/python] fix: disable RFC5280 validation

explorer/nodewatch/nodewatch/RoutesFacade.py, explorer/nodewatch/nodewatch/__init__.py, explorer/nodewatch/tests/test_RoutesFacade.py, explorer/nodewatch/tests/test_app.py
Problem: The endpoint is missing when using the main public key to query node info.
Solution: 
- Added a new endpoint to query node info by the main public key.
- Added error handler for 400 and 404
=> [explorer/nodewatch]: added new endpoint to query node by main public key

explorer/nodewatch/nodewatch/__init__.py, explorer/nodewatch/tests/test_app.py
Problem: The endpoint is missing when using the node public key to query node info.
Solution: 
- Added a new endpoint to query node info by the node public key.
=> [explorer/nodewatch]: added new endpoint to query node by node public key

explorer/frontend/README.md, explorer/frontend/docker-compose.yaml, explorer/frontend/next.config.js
The Next.js build was not runnable inside a Docker container outside the Vercel environment due to the missing `output: 'standalone'` configuration. 
The Docker Compose volume mapping for the accounts directory was incorrect.
- Added `output: 'standalone'` to `next.config.js`.
- Updated the Docker Compose volume mapping from `./accounts:/app/public/accounts` to `./public/accounts:/app/public/accounts`.
- Updated the README.
```
=> [explorer/frontend] fix: next.js config for docker support

explorer/nodewatch/nodewatch/NetworkRepository.py, explorer/nodewatch/tests/resources/symbol_nodes.json, explorer/nodewatch/tests/test_NetworkRepository.py, explorer/nodewatch/tests/test_RoutesFacade.py
Problem: The API node status field is missing.
Solution: Added API node status properties in **NodeDescriptor**.
=> [explorer/nodewatch]: added api node status field

tools/shoestring/shoestring/commands/upgrade.py
problem: the config patch operation fails due to an invalid path in the config-harvesting.properties file.
the patch() method only requires the filename.
solution: pass only the filename to the configuration manager patch method
```
File "/lib/python3.12/site-packages/shoestring/internal/ConfigurationManager.py", line 48, in patch
with open(config_filepath, 'rt', encoding='utf8') as infile:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'userconfig/resources/userconfig/resources/config-harvesting.properties'
```
The reason why tests are passing is that the [absolute path](https://docs.python.org/3/library/pathlib.html#operators) is used.
=> [tools/shoestring] fix: upgrade command fails with harvesting node

explorer/nodewatch/nodewatch/RoutesFacade.py, explorer/nodewatch/nodewatch/__init__.py, explorer/nodewatch/tests/test_RoutesFacade.py, explorer/nodewatch/tests/test_app.py
Problem: The filter node is missing on the API node list endpoint.
Solution: Added query params `only_ssl`, `limit`, and `order`.
`only_ssl`: to filter out SSL enable node, it needs explorer and wallet.
`limit`: the number of numbers returned from the endpoint.
`order`: shuffle node list when required
=> [explorer/nodewatch]: Added query params for get node list endpoint

tools/shoestring/shoestring/commands/upgrade.py, tools/shoestring/tests/commands/test_upgrade.py
problem: shoestring upgrade fails to delete the recovery docker compose due to it not present
solution: ignore unlink failure for the docker compose recovery file since it does not exist
=> [tools/shoestring] fix: fail to delete docker compose recover on upgrade

tools/shoestring/shoestring/internal/ConfigurationManager.py, tools/shoestring/shoestring/wizard/setup_file_generator.py, tools/shoestring/shoestring/wizard/shoestring_dispatcher.py, tools/shoestring/tests/internal/test_ConfigurationManager.py, tools/shoestring/tests/wizard/test_setup_file_generator.py, tools/shoestring/tests/wizard/test_shoestring_dispatcher.py
problem: shoestring wizard upgrade does not upgrade to the latest release
this is because latest package config is not downloaded
solution: download the latest package config while keeping user config
=> [tools/shoestring] fix: wizard upgrade does not get latest package file

lightapi/python/scripts/ci/publish.sh
problem: twine shipped with Ubuntu is outdated and fails with newer metadata versions
solution: use twine from the local Python environment
for the test package, publish to our internal repository
=> [lightapi/python] fix: publish fails due to older twine version

lightapi/python/tests/connector/test_BasicConnector.py, lightapi/python/tests/connector/test_NemConnector.py, lightapi/python/tests/connector/test_SymbolConnector.py
problem: in pytest asyncio v1 the event loop was removed
solution: remove the dependency on event loop and convert fixures and tests to async where needed
=> [lightapi/python] fix: pytest asyncio removed event loop

lightapi/python/pyproject.toml
problem: zenlog is calling deprecated warn function on Logger object from logger library
solution: configure pytest to ignore these warnings
=> [lightapi/python]: ignore deprecation warnings raised by zenlog library

tools/shoestring/shoestring/wizard/ValidatingTextBox.py, tools/shoestring/tests/wizard/test_ValidatingTextBox.py
- When entering a hostname that starts with a dot (e.g. `.example.com`) in the wizard, an exception occurs and a stack trace is displayed.
- Although a `UnicodeError` is being raised, it can also be caught as a `ValueError`, so the exception handling is adjusted to catch `ValueError` to match the surrounding code.
=> [tools/shoestring] fix: exception handling during hostname validation in the wizard

lightapi/python/symbollightapi/connector/ConnectorExtensions.py, lightapi/python/symbollightapi/connector/SymbolConnector.py, lightapi/python/tests/connector/test_ConnectorExtensions.py, lightapi/python/tests/connector/test_SymbolConnector.py
problem: transactions/confirmed does not seem to be returning transactions in desc order
solution: explicitly specify desc order
=> [lightapi/python]: explicitly order Symbol transactions in desc order

lightapi/python/requirements.txt, lightapi/python/symbollightapi/connector/ConnectorExtensions.py, lightapi/python/symbollightapi/connector/NemConnector.py, lightapi/python/symbollightapi/connector/SymbolConnector.py, lightapi/python/symbollightapi/model/Constants.py, lightapi/python/tests/connector/test_ConnectorExtensions.py, lightapi/python/tests/connector/test_NemConnector.py, lightapi/python/tests/connector/test_SymbolConnector.py
[lightapi/python]: add query_block_timestamps
problem: need to lookup timestamps of block heights
solution: add query_block_timestamps extension
add block_headers to SymbolConnector
[lightapi/python]: add filter_finalized_transactions
problem: need to select finalized transactions from a group of transactions
solution: add filter_finalized_transactions extension
add filter_confirmed_transactions to SymbolConnector and NemConnector
=> [lightapi/python]: add a few more needed extensions

bridge/bridge/db/WrapRequestDatabase.py, bridge/requirements.txt, bridge/tests/db/test_WrapRequestDatabase.py, bridge/workflows/calculate_conversion.py, bridge/workflows/check_finalized_transactions.py
problem: after sending payout transactions need to monitor their completion
solution: add workflow for tracking payout transactions
rework WrapRequestDatabase to store all required information
=> [bridge]: add workflow for checking completed wrap payout transactions

bridge/bridge/nem/NemNetworkFacade.py, bridge/bridge/nem/NemUtils.py, bridge/bridge/symbol/SymbolNetworkFacade.py, bridge/bridge/symbol/SymbolUtils.py, bridge/tests/nem/test_NemNetworkFacade.py, bridge/tests/nem/test_NemUtils.py, bridge/tests/symbol/test_SymbolNetworkFacade.py, bridge/tests/symbol/test_SymbolUtils.py, bridge/tests/test/PytestUtils.py
[bridge]: update network facades to support arbitrary mosaics
problem: network facades primarily support currency mosaic operations
solution: generalize to supporting arbitrary mosaics
[bridge]: fix some naming issues in tests
problem: inconsistent namings should be fixed
solution: rename can_create_wrap_request_*
* can(not)_create_wrap_request_* => can(not)_extract_wrap_request_*
* transaction_meta_json => transaction_with_meta_json
=> [bridge]: update network facades to support arbitrary mosaics

faucet/frontend/components/nem/config/default.json, faucet/frontend/components/symbol/config/default.json
Problem: The Discord link is outdated.
Solution: Updated the latest link.
=> [faucet/frontend] fix: update discord link

bridge/bridge/ethereum/EthereumAdapters.py, bridge/tests/ethereum/test_EthereumAdapters.py, bridge/tests/ethereum/test_EthereumConnector.py, bridge/tests/ethereum/test_EthereumNetworkFacade.py, bridge/tests/test/MockEthereumServer.py
problem: prior to signing, eth_account checks if (string) address matches checksum address
since string representation used is uppercase, it will not match and signing fails
solution: change EthereumAddress str to return checksum address
=> [bridge]: use checksum addresses or eth libraries will not work

bridge/bridge/CoinGeckoConnector.py, bridge/bridge/ConversionRateCalculatorFactory.py, bridge/bridge/NetworkUtils.py, bridge/bridge/ethereum/EthereumConnector.py, bridge/bridge/ethereum/EthereumNetworkFacade.py, bridge/bridge/models/BridgeConfiguration.py, bridge/bridge/nem/NemNetworkFacade.py, bridge/bridge/symbol/SymbolNetworkFacade.py, bridge/tests/ethereum/test_EthereumConnector.py, bridge/tests/ethereum/test_EthereumNetworkFacade.py, bridge/tests/models/test_BridgeConfiguration.py, bridge/tests/nem/test_NemNetworkFacade.py, bridge/tests/test/MockEthereumServer.py, bridge/tests/test_CoinGeckoConnector.py, bridge/tests/test_NetworkFacadeLoader.py, bridge/tests/test_NetworkUtils.py, bridge/workflows/check_finalized_transactions.py, bridge/workflows/download_balance_changes.py, bridge/workflows/download_wrap_requests.py, bridge/workflows/main_impl.py, bridge/workflows/send_payouts.py
[bridge]: add price oracle for fee conversions
problem: when sending transactions on wrapped network fees need to be from native currency to wrapped token
solution: add and integrate CoinGecko connector (price oracle)
[bridge]: add ethereum transaction fee calculation
problem: ethereum fees are hardcoded
solution: calculate fees dynamically
=> [bridge]: add ETH fee calculation and convert fees into wrapped token units

tools/shoestring/tests/wizard/test_TabbedView.py
problem: latest prompt_toolkit removed extra space at the end of output
solution: remove extra space after the last tab
=> [tools/shoestring] fix: show tabs test failing

explorer/nodewatch/nodewatch/NetworkRepository.py, explorer/nodewatch/nodewatch/RoutesFacade.py, explorer/nodewatch/nodewatch/__init__.py, explorer/nodewatch/nodewatch/templates/base.html, explorer/nodewatch/nodewatch/templates/symbol_nodes.html, explorer/nodewatch/tests/test_NetworkRepository.py, explorer/nodewatch/tests/test_RoutesFacade.py, explorer/nodewatch/tests/test_app.py
Problem: Page was missing finalized information and voting key expiry info.
Solution: Added finalized information at the header and voting key expiry column in the voter table.
Before:
After:
=> [explorer/nodewatch]: added finalized information in header and voter page

README.md
The wallet/common-symbol project is missing in monorepo readme
Add wallet/common-symbol project to monorepo readme
=> [monorepo] feat: add wallet/common-symbol project to readme

explorer/nodewatch/nodewatch/RoutesFacade.py, explorer/nodewatch/tests/test_RoutesFacade.py
Problem: the latest client version turns to red.
Solution: update the version list
=> [explorer/nodewatch] fix: update version colors

explorer/nodewatch/nodewatch/NetworkConnector.py, explorer/nodewatch/tests/test_NetworkConnector.py
problem: some nodes are failing with ServerDisconnectedError, which is not handled
solution: handle the ServerDisconnectedError exception
also, fix finalized info not getting handled in the refresh task
=> [explorer/nodewatch] fix: refresh height task failing
